### ISSUE TITLE
Reporte de Entrevista

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/entrevista-alfa-dinamita#1]
[Reporte de entrevista.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-alfa-dinamita/files/7166092/Reporte.de.entrevista.pdf)

https://drive.google.com/drive/folders/1L_V0G_0KqKVzbRez8-T8xuRUhdPN1RqJ?usp=sharing  (Audio de la entrevista)

**Comment by kirus21** [comment]
Calificación: 18/20
Califico: Rigoberto Suridaí Pascual Reyes

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
